# summary: RedHat specific variables
# type: Ansible Vars
# author: Urs Roesch <roesch@puzzle.ch>
# description: |
#  Specific variables that match the OS
#  family RedHat such as packages.
---
packer_os_family: redhat
packer_walinuxagent_package: WALinuxAgent
packer_walinuxagent_service: waagent
packer_cloudinit_packages:
  - cloud-init
packer_common_packages:
  - cloud-init
  - virt-what
  - openssl
  - tar
packer_common_hyperv_packages:
  - hyperv-daemons
  - hyperv-tools
packer_common_vmware_packages:
  - open-vm-tools
  - perl
packer_regenerate_grub_command: |2+
  for cfg in /etc/grub2*.cfg; do
    grub2-mkconfig -o `readlink -e ${cfg}`
  done
