# summary: RHEL 7 and derivated specific variables
# type: Ansible Vars
# author: Urs Roesch <roesch@puzzle.ch>
# description: |
#  Specific variables that match the OS
#  family CentOS such as packages.
---
packer_centos_gpg_url: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7
packer_dist_short: el7
packer_packages:
  - epel-release
  - "{{ packer_common_packages }}"
packer_hyperv_packages:
  - "{{ packer_common_hyperv_packages }}"
packer_vmware_packages:
  - python-netifaces
  - "{{ packer_common_vmware_packages }}"

# path to dhcp.py file which requires patching.
packer_cloudinit_dhcp_file: /usr/lib/python2.7/site-packages/cloudinit/net/dhcp.py
