# summary: openSuse Leap specific variables
# type: Ansible Vars
# author: Urs Roesch <roesch@puzzle.ch>
# description: |
#  Specific variables that match the OS
#  distribution openSuse 15 such as packages.
---
packer_centos_gpg_url: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7
packer_dist_short: sl15
packer_packages:
  - "{{ packer_common_packages }}"
packer_vmware_packages:
  - "{{ packer_common_vmware_packages }}"
packer_suse_repos:
  #- name: Virtualization
  #  repo: https://download.opensuse.org/repositories/Virtualization/SLE_15_SP3/
  #- name: Cloud_Config
  #  repo: https://download.opensuse.org/repositories/Cloud:/Tools/SLE_15_SP3/
  #- name: devel_languages_python_backports
  #  repo: https://download.opensuse.org/repositories/devel:languages:python:backports/SLE_15_SP3/
  - name: LEAP_15_SP5
    repo: http://download.opensuse.org/distribution/leap/15.2/repo/oss/

# path to dhcp.py file which requires patching.
packer_cloudinit_dhcp_file: /usr/lib/python3.6/site-packages/cloudinit/net/dhcp.py
