# summary: Suse Linux Enterprise specific variables
# type: Ansible Vars
# author: Urs Roesch <roesch@puzzle.ch>
# description: |
#  Specific variables that match the OS
#  distribution openSuse 15 such as packages.
---
packer_packages:
  - "{{ packer_common_packages }}"
packer_vmware_packages:
  - "{{ packer_common_vmware_packages }}"
