# title: Manage VMWare specific tools configurations
# author: Urs Roesch <roesch@puzzle.ch>
# description: |
#   Install the open-vm-tools and do configurations
---
- block:
  - name: firstboot - install firstboot systemd services on ubuntu
    copy:
      dest: /etc/systemd/system/ssh-firstboot.service
      owner: root
      group: root
      mode: '0644'
      content: |
        # Run on VMware before sshd to create the ssh host keys
        [Unit]
        Description=Generate SSH Keys on VMWare
        Before=ssh.service
        #
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ssh-keygen -A
        ExecStartPost=/usr/bin/rm /etc/systemd/system/ssh-firstboot.service
        #
        [Install]
        WantedBy=multi-user.target

  - name: firstboot - enable service
    systemd:
      name: ssh-firstboot
      enabled: yes

  when:
    - packer_distribution == 'ubuntu'
